### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by jvcasillas** [learnB4SS/learnB4SS.github.io#1]
I suggest we consider a hugo/blogdown workflow. Here are a few minimalist designs I like: 

- https://blogophonic-hugo.netlify.app
- https://themes.gohugo.io/theme/etch/
- https://adityatelange.github.io/hugo-PaperMod/
- https://themes.gohugo.io/theme/hugo-theme-hello-friend-ng/
- https://ublogger.netlify.app

**Comment by jvcasillas** [comment]
I created the template site using blogophonic (we can change later if we decide we don't want it).

**Comment by stefanocoretta** [comment]
https://learnb4ss.github.io
Still need to add dates and fix up style. Lemme know.

**Comment by jvcasillas** [comment]
Looks cool!

**Comment by jvcasillas** [comment]
- twitter: jvcasill
- website: www.jvcasillas.com
- email: hell naw

**Comment by stefanocoretta** [comment]
Website updated. Lemme know what could be improved (you might have to clear your browser cache to see the changes).

**Comment by stefanocoretta** [comment]
P.S. @troettge can you upload the B4SS hexlogo to this repo, in `img/`? SVG would be best.

**Comment by troettge** [comment]
@stefanocoretta: 

1. logo is uploaded
2. I know I am a pain in the ass, and this way is not the best way to give design feedback, but: can we rearrange things and change colors
  - The orange section right at the beginning might be a bit much. The contrast with white is not great either.
  - so 1st section the dark grey (highlight LEARN with orange); 
  - 2nd section: DO YOU WANT TO LEARN BAYESIAN DATA ANALYSIS? Section background in orange, font color, black; 
  - 3rd section. WHY BAYESIAN, then 4th section: The workshop. One thing that is missing is a reference to labphon, I think they would appreciate a reference, a link to their page. Also registration will be handled by them, meaning, we need to refer to them, but we can ask for specifics and details. 
  - Finally, I vote for taking out our "titles", there is no additional value to knowing that I am faculty and you are not. Doesn'T matter and I don't want to suggest hierarchy (also because the titles are not translatable across systems: My position is an entry level as is Josephs. As it stands it looks like I am in any way more senior which I am neither conceptually nor formally). Does that make sense?

**Comment by stefanocoretta** [comment]
Sure. no probs! I'll work on that later today or tomoz. Unless you guys wanna play with it, i'ts just plain html/css.

**Comment by stefanocoretta** [comment]
Done! Ideas on how to include LabPhon?

**Comment by stefanocoretta** [comment]
Just noticed that the subtitle in the logo is not really visible so better to take out. Timo, could you please upload a vector version of the logo as an `.svg` file? The one you uploaded in `.svg` but the logo is raster. :D

**Comment by troettge** [comment]
@stefanocoretta logo as svg up
@jvcasillas keynote for branding up

**Comment by stefanocoretta** [comment]
@troettge I don't have the typeface in the logo. Let's do this, can you upload a second version of the logo without subtitle, for smaller logo sizes?
